### ISSUE TITLE
get the whole image rendered 

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [flbulgarelli/headbreaker#10]
Am having problem to get the whole image to render,  when i pick an image it only show the half of it .

eg.

https://flbulgarelli.github.io/headbreaker/#validated

it only show the half, is there way to fully render the image into pieces?

**Comment by flbulgarelli** [comment]
Hi!

Currently there is no way to adjust _at the same time_ the image width and height to the x and y axis - either you have to adjust one of them and ensure the other dimension of the image has the proper size. So basically you need to have images which proper aspect ratios. 

However,  you can adjust one of the axis using `adjustImagesToPuzzleHeight` or `adjustImagesToPuzzleWidth` methods - or the generic `adjustImagesToPuzzle` which takes an axis.  Docs are [here ](https://flbulgarelli.github.io/headbreaker/api/Canvas.html) and here [is an example](https://flbulgarelli.github.io/headbreaker/#background). 

Also, [here](https://mumuki.github.io/mumuki-puzzle-runner/docs/ ) you may find more sophisticated adjustment scenarios on top of headbreaker. However although adjustment axis are calculated dynamically, they ultimately rely on the aforementioned methods. 

PS: there are also `adjustImagesToPiece.*` counterparts for those methods, but I assume you want images adjusted to the whole puzzle, not to a single piece.

I hope this helps!
