### ISSUE TITLE
open source / license?

### ISSUE THREAD

**Issue by jtkeyva** [flbulgarelli/headbreaker#12]
hello, wondering if you are open sourcing this or putting a license on it?
thanks

**Comment by flbulgarelli** [comment]
Hi @jtkeyva!

This project is delivered under ISC, as stated on package.json. I have just also added a corresponding LICENCE file https://github.com/flbulgarelli/headbreaker/commit/3c96dc944e4efd53aeec960acb6efc77f387c160.
