### ISSUE TITLE
Standalone Javascript

### ISSUE THREAD

**Issue by ghostdlr** [flbulgarelli/headbreaker#15]
Hi

How do I build this library as a standalone Javascript, not as a node package?

I see the demo uses a full js file, but it is minified:  https://flbulgarelli.github.io/headbreaker/js/headbreaker.js .
Can you post the unminified version please?  I don't want to use Node.js for my project.

**Comment by flbulgarelli** [comment]
Hi @ghostdlr!

You could locally install it using node and building a non-minified bundle of it using webpack. Also, you can just clone this repo and build a development version with the already provided webpack tasks. Then, you will be able to add it to your project. 

Hope that helps!
