### ISSUE TITLE
How can I replace the image of a single piece?

### ISSUE THREAD

**Issue by anotherstarburst** [flbulgarelli/headbreaker#16]
Hello. I'm having quite a bit of fun with this library! Right now I'm experimenting with replacing the image of a single piece during the game. My set up is as follows

```javascript
const headbreakerPuzzle = new headbreaker.Canvas('#puzzle', {
  width,
  height,
  pieceSize,
  proximity: 20,
  borderFill: 10,
  strokeWidth: 1.5,
  fixed: false, 
  image: puzzleImage,
  outline: new headbreaker.outline.Rounded(),
  preventOffstageDrag: true,
  maxPiecesCount: horizontalPiecesCount * verticalPiecesCount,
});
```

I've found I can replace a single piece image using

```javascript
const replacementImage = new Image();
replacementImage.src = '...'
replacementImage.onload = () => {
  const figureKey = "2";
  headbreakerPuzzle.figures[figureKey].shape.fillPatternImage(replacementImage);
  ...
  headbreakerPuzzle.figures[figureKey].shape.fillPatternOffsetX(fillPatternOffsetX);
  headbreakerPuzzle.figures[figureKey].shape.fillPatternOffsetY(fillPatternOffsetY);
  ...
}
```

Unfortunately I'm having difficulty calculating `fillPatternOffsetX` and `fillPatternOffsetY` where a piece has tabs. Pieces with only slots work fine. 

My initial guess was that the offset would be `bezelDepth * pieceSize`  where `pieceSize` was defined during canvas setup and `bezelDepth` is defined at https://github.com/flbulgarelli/headbreaker/blob/c5bd65720fdb091163058ff6b873a6091b7f780f/src/outline.js#L70

But the image remains offset. The offset also changes depending on the number of tabs e.g. it's different for "TST-" and "SST-". 

I've tried a few iterations of `1/5 * pieceSize`, `2/5 * pieceSize`, etc. I get close for some pieces, but it's never exact, and doesn't work for the different iterations (e.g. the "TST-" and "SST-" mentioned before)

What is the appropriate way to calculate the offset?

**Comment by anotherstarburst** [comment]
I have also tried

[const r = Math.trunc(this.referenceInsertAxisLength(fullSize) * (1 - 2 * this.borderLength) * 100) / 100;](https://github.com/flbulgarelli/headbreaker/blob/c5bd65720fdb091163058ff6b873a6091b7f780f/src/outline.js#L101)

as 

`
const borderLength = 1/3; // defined on line 72
const tabLength = Math.trunc(pieceSize * (1 - 2 * borderLength) * 100) / 100
`

**Comment by anotherstarburst** [comment]
Also, looking at https://github.com/flbulgarelli/headbreaker/blob/c5bd65720fdb091163058ff6b873a6091b7f780f/test/outline-spec.js 

it seems that the inserts are 1/3 of the `pieceSize`, but no dice with that as

`const fillPatternOffsetX = Math.trunc(pieceSize * 1 / 3 * 100) / 100;`

**Comment by flbulgarelli** [comment]
Hi!

This is not completely converted out-of-the box by `headbreaker`. However, it is still doable. Here there is an example: https://mumuki.github.io/mumuki-puzzle-runner/docs/. 

[Here](https://github.com/mumuki/mumuki-puzzle-runner/blob/master/lib/public/js/muzzle.js) is the code you can use as _inspiration_, since it is not pretty generic but tied to [mumuki](https://github.com/mumuki/) - the project where we use those puzzles.

**Comment by anotherstarburst** [comment]
Thanks @flbulgarelli - I'll take a look!
