### ISSUE TITLE
Hi - Pieces "Bank"

### ISSUE THREAD

**Issue by djroy25** [flbulgarelli/headbreaker#17]
Hi, 

When using the line shuffle the pieces goes outside of the the canvas.

Is it possible to add a "Bank" of the pieces with
 horizontal scroll to it? attached an image

![puzzle-bank](https://user-images.githubusercontent.com/16280820/160271954-5b8a3f71-7e4f-4b24-8f47-e347cc01bec6.png)

Thanks,

**Comment by flbulgarelli** [comment]
Hi @djroy25, 

Unfortunately, there is no current support for pieces' banks like you proposed. However, yoy should be able to control the pieces going out of canvas at some degree. Just use the distance parameter when [shuffling](https://flbulgarelli.github.io/headbreaker/api/Canvas.html) the canvas, e.g.  `canvas.shuffle(0.8)`. 

I suggest to check the _shuffle_ buttons in the demo at https://flbulgarelli.github.io/headbreaker/. Please check that pieces don't ever - completely - go off-stage.
