### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by Nikittansk** [flbulgarelli/headbreaker#19]
Hello!
Your library is very much needed for the project.
But I can't figure out how to use it normally in JavaScript, without Node.js

**Comment by flbulgarelli** [comment]
Hi @Nikittansk!

Please check this question: https://github.com/flbulgarelli/headbreaker/issues/15. Although you don't need to use nodejs on runtime and you can build and bundle and serve headbreaker code statically, you will still need to use npm and a bundler like [webpack](https://webpack.js.org/) to integrate it in your project. 

Hope this helps
