### ISSUE TITLE
Moving pieces offstage if preventOffstageDrag AND fixed are true

### ISSUE THREAD

**Issue by sluedecke** [flbulgarelli/headbreaker#25]
Thanks for this truly great library!

One can set a Canvas to have `preventOffstageDrag` and `fixed` to true.  While the first prevents a piece from being moved offstage (good thing!) one can move a group of connected pieces in such a way that all other connected pieces will go offstage.  With `fixed = true` there is no way to access the now "lost" pieces.

Any idea how to prevent this?

**Comment by flbulgarelli** [comment]
Hi @sluedecke, thank you for your comments. 

There is no out-of-the-box solution to the problem you are describing. Although it may be tricky, you could implement this functionality on top of `hadbreaker`. 

One option is to access the underlying konva [Layer](https://konvajs.org/api/Konva.Layer.html) instance - `yourCanvas.__konvaLayer__` - and perform manual translations, or even register a hook to prevent movement by taking into account the whole set of pieces. 

Alternatively you may achieve the same goals at the logical level, by controlling your `puzzle` object. For example, you could implement a center-button functionality that translates the whole puzzle using the offstage delta. Here there is a small snippet that may serve you as starting point: 

```javascript
// if your pieces went offstage on the left side, their x axis will be negative
const delta = - Math.min(...validated.puzzle.pieces.map(it => it.leftAnchor.x));
validated.puzzle.translate(delta, 0);
validated.redraw();

// if your pieces went offstage to the right, their x axis will exceed the canvas width
const deltaX =  validated.width -  Math.max(...validated.puzzle.pieces.map(it => it.rightAnchor.x))
validated.puzzle.translate(delta, 0);
validated.redraw();

// the same goes for the y axis
```

**Comment by Faycal88** [comment]
I was able to find a solution to that, but with longer code  
Also it is not very stable so if anyone can make it better , they are very welcome to 

`   canvas.__konvaLayer__.children.addEventListener("xChange", (e) => {
        const delta = Math.min(
          ...canvas.puzzle.pieces.map((it) => it.leftAnchor.x)
        );
        const deltaX =
          canvas.width -
          Math.max(...canvas.puzzle.pieces.map((it) => it.rightAnchor.x));

        if (delta < 0) {
          const piece = canvas.puzzle.pieces.findIndex((i) =>
            i.leftAnchor.x < 0 ? i : null
          );
          if ((piece) => 0) {
            canvas.puzzle.pieces[piece].translate(0.1, 0);

            canvas.redraw();
          }
        }

        if (deltaX < 0) {
          const piece = canvas.puzzle.pieces.findIndex((i) =>
            i.rightAnchor.x > canvas.width ? i : null
          );
          if ((piece) => 0) {
            canvas.puzzle.pieces[piece].translate(0.1, 0);
            canvas.redraw();
          }
        }
      });

      canvas.__konvaLayer__.children.addEventListener("yChange", (e) => {
        const delta = Math.min(
          ...canvas.puzzle.pieces.map((it) => it.upAnchor.y)
        );
        var deltaY = Math.min(
          ...canvas.puzzle.pieces.map((it) => it.downAnchor.y)
        );
        if (delta < 0) {
          const piece = canvas.puzzle.pieces.findIndex((i) =>
            i.upAnchor.y < 0 ? i : null
          );
          if ((piece) => 0) {
            canvas.puzzle.pieces[piece].translate(0, 0.1);
            canvas.redraw();
          }
        }
        if (deltaY - canvas.height < 70) {
          // could not figureout the downAnchor Part
          const piece = canvas.puzzle.pieces.findIndex((i) =>
            i.downAnchor.y < 0 ? i : null
          );
          console.log(piece);
          return (piece) =>
            0
              ? canvas.puzzle.pieces[piece].translate(0, -0.1) &&
                canvas.redraw()
              : null;
        }
      }); `

**Comment by flbulgarelli** [comment]
Hi! I have just released a new version with explicit support for explicitly translating pieces into visible area. See https://github.com/flbulgarelli/headbreaker/pull/31. 

With this change, you can recover recover off-stage pieces out-of-the-box, and it should be easier to keep pieces within bounds using an even-based approach. 

I am closing this issue by now.
