### ISSUE TITLE
Positioning Puzzle on Canvas in autogenerate

### ISSUE THREAD

**Issue by jwotman** [flbulgarelli/headbreaker#5]
I assumed I could do this to set the position of the puzzle:
puzzle.autogenerate({
              horizontalPiecesCount: 6,
              insertsGenerator: headbreaker.generators.random,
              metadata: {currentPosition: [300,100] }
            });
The metadata doesn't have any affect on puzzle position.

**Comment by flbulgarelli** [comment]
Hi!

I think you may have two issues here: 

1. You positions are vectors expressed as `{x, y}` objects, not pairs expressed as two-elements-lists. You could try using `headbreaker.vector(300, 100)` or `{x:300, y:100}`
2. The metadata accepted by `autogenerate` is a list of `metadata`s, that will be zipped to each of the generated pieces, if present. That means that you may individually specify the current position of each piece, but not a general current position for all of them. 

Please try the following: 

```javascript
puzzle.autogenerate({
  horizontalPiecesCount: 6,
  insertsGenerator: headbreaker.generators.random,
  metadata: [{currentPosition: {x:300, y:100} }]
});
```

Which generates the following puzzle: 

![image](https://user-images.githubusercontent.com/677436/92268713-4dcf1980-eeb9-11ea-8f40-93e276a89e79.png)
