### ISSUE TITLE
Separate containers to hold all pieces, outside the puzzle area

### ISSUE THREAD

**Issue by nirvitarka** [flbulgarelli/headbreaker#52]
**Is your feature request related to a problem? Please describe.**
Can we show all pieces in separate container with an empty puzzle area?

**Describe the solution you'd like**
A scrollable area holding all puzzle pieces outside the actual puzzle area should be configurable

**Comment by flbulgarelli** [comment]
:wave: Hi! The short answer is that there is no explicit support for this feature, and it probably won't be since it is currently out of the scope of the framework. You could create that on top of it, though. See https://github.com/flbulgarelli/headbreaker/issues/17.
