### ISSUE TITLE
Headbreaker.js seems to be broken

### ISSUE THREAD

**Issue by CodeByCalvin** [flbulgarelli/headbreaker#65]
I've started to make a project using Headbreaker. This code worked around 3 weeks ago but having just opened the project, I now get the below error (which seems to trace back to Headbreaker.js). I can see there has been an update to the repo 2 weeks ago which presumably is related; though I'm not sure if this is a bug or a change to my code that I now need to make?

```
headbreaker.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at a (headbreaker.js:1:62775)
    at Object.multiply (headbreaker.js:1:63182)
    at t.exports.sketch (headbreaker.js:1:134292)
    at Canvas.renderPiece (canvas.js:179:1)
    at canvas.js:201:1
    at Array.forEach (<anonymous>)
    at Canvas.renderPieces (canvas.js:199:1)
    at Canvas.autogenerateWithManufacturer (canvas.js:242:1)
    at Canvas.autogenerate (canvas.js:232:1)
    at backgroundImg.onload (jigsaw.jsx:23:1)
```

This is my React component which contains the jigsaw.

```
import React, { useEffect } from "react";
import headbreaker from "headbreaker";
import { useState } from "react";

const Jigsaw = (props) => {
  // Jigsaw with image
  useEffect(() => {
    const backgroundImg = new Image();
    backgroundImg.src = props.image || "";
    backgroundImg.onload = () => {
      const autogen = new headbreaker.Canvas("autogen-canvas", {
        width: 800,
        height: 650,
        pieceSize: props.pieceSize,
        proximity: 20,
        borderFill: props.pieceSpacing,
        strokeWidth: 1.5,
        lineSoftness: 0.18,
        image: backgroundImg,
      });

      autogen.adjustImagesToPuzzleHeight();
      autogen.autogenerate({
        horizontalPiecesCount: props.horizontalPieces,
        verticalPiecesCount: props.verticalPieces,
      });
      autogen.draw();
    };
  }, [
    props.horizontalPieces,
    props.verticalPieces,
    props.pieceSize,
    props.pieceSpacing,
    props.image,
  ]);

  return (
    <div>
      <div id="autogen-canvas"></div>
    </div>
  );
};

export default Jigsaw;

```

**Comment by flbulgarelli** [comment]
Hi!

That is true, the latest published version - 3.0 - has a few breaking changes. Also, since the precompiled version you are using always points to latest changes, you will need to adapt your code - or continue using the previous version as an mom package.

That said, your code looks right, I don't see any broken code there. However, I think the problem may come from your props, in particular the `pieceSize`. I suspect your are passing a `radio` instead of a `radius` - which is a property which was renamed.

I hope that helps!

**Comment by CodeByCalvin** [comment]
Aaaah I see. Ideally I would like to update my code so it works with the latest version, but just in-case, how would I install the older version, would it be: `npm install headbreaker@2.0.0` ?

I did check the commit that changed radio to radius, but I'm not sure if this applies to me or not. The prop I pass is an integer from a slider that updates a 'pieceSize' useState() (starting at 150) which is then passed to my generated jigsaw in jigsaw.jsx.

```
 const [pieceSize, setPieceSize] = useState(150);
  const handlePieceSizeChange = (event) => {
    setPieceSize(parseInt(event.target.value));
  };

...

<Jigsaw
        horizontalPieces={horizontalPieces}
        verticalPieces={verticalPieces}
        pieceSize={pieceSize}
        pieceSpacing={pieceSpacing}
        image={uploadedImage}
/>

 <Sidebar
      ...
        onPieceSizeChange={handlePieceSizeChange}
       ...
/>
```

**Comment by CodeByCalvin** [comment]
Hi!

Apologies for such a delayed response, I've have a few IRL commitments/holiday that has overruled the coding. Thank you very much for taking the time to have a look and respond to me!

I've got my repo here (https://github.com/CodeByCalvin/Jigsaw-Reward-Tracker) if that works, or does it need to be in a service like CodePen?

**Comment by flbulgarelli** [comment]
> I've got my repo here (https://github.com/CodeByCalvin/Jigsaw-Reward-Tracker) if that works, or does it need to be in a service like CodePen?

Hi @CodeByCalvin! Yes, please provide a minimal working CodePen or equivalent, so that I can reproduce the problem easily. Thanks.

**Comment by CodeByCalvin** [comment]
I started to remake my project in Next.js and used the very helpful React sample code as a starting point which all seems to work. I think the presence of "painter: new headbreaker.painters.Konva()," might be the thing that allows my puzzle to now render, though I'm not 100% sure. Thank you! 😄
