### ISSUE TITLE
Limit the drag  

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [flbulgarelli/headbreaker#7]
is there way to limit the Piece drag behavior, to make them drag able within the `Canvas`. In other word the Piece disappear when i drag them outside of the `Canvas`. So is there way to stop that ?

**Comment by nabiloo19** [comment]
i have the same problem

**Comment by flbulgarelli** [comment]
Hi @Mohamed-Kaizen and @nabiloo19! 

There is currently no out-of-the-box support for that, but [here there are](https://github.com/flbulgarelli/headbreaker/issues/2) some workarounds for it: 

1. setting a draggable background 
2. adding css blur around the canvas border - something similar to https://github.com/mumuki/mumuki-puzzle-runner/commit/ed7127eee6901ece1426bb83ef185525708ca464

A better approach would be to include some kind of boundary in the piece model, around here https://github.com/flbulgarelli/headbreaker/blob/master/src/piece.js#L373. Checking that translation is within bounds + on-demand disconnection should be enough to prevent out-of-stage single piece movement, but a better bounds checking to prevent whose pieces group going out of stage needs a bit more logic.

I may implement that on the future but on the meanwhile PRs are welcomed!

**Comment by Mohamed-Kaizen** [comment]
we found solution thanks to @Almo7aya you can check it here 

https://github.com/Almo7aya/headbreaker/commit/1c6d890ea458e5865f1079ad1a17e7dcd3c69b59#diff-f15bc8498764366681a8e1347481a3ac35ab72d16a21baad88e13e9514d2eaf3R112

**Comment by flbulgarelli** [comment]
Nice catch :clap:. I'll pick it into next release!
