### ISSUE TITLE
Drawing our own shapes

### ISSUE THREAD

**Issue by nabiloo19** [flbulgarelli/headbreaker#8]
Can I draw my own shapes? I believe that the game needs to be reshaped with my own design

**Comment by flbulgarelli** [comment]
Hi! Yes, you can achieve that using `outlines`. 

Please check out this example: https://flbulgarelli.github.io/headbreaker/#rounded-lines.

`headbreaker` comes with two outline classes: `Rounded` and `Squared`, both of them are inside https://github.com/flbulgarelli/headbreaker/blob/master/src/outline.js. You can use them or provided your own outline to the canvas (`outline` property). 

An `outline` is a plain old class or object that has a `draw` method, which takes a piece and a few more options. Within that method, you may return the list of points of the shape you want to achieve. Points will be interpreted as normal o bezier depending on the `isBezier` method..

**Comment by nabiloo19** [comment]
Thanks :) 🙏
